ACCESS_TOKEN_URL_PATH = "/account/desktop-app/access-token/"
BOILERPLATE_CONFIG_FILENAME = "boilerplate.json"
ADDON_CONFIG_FILENAME = "addon.json"
ALDRYN_DOT_FILE = ".aldryn"
DOCKER_TEST_IMAGE = "busybox:1.30"
